import 'package:package_info_plus/package_info_plus.dart';

part 'package_info_service.dart';

/// Service for retrieving application package information.
abstract class InfoService {
  /// Creates a new [InfoService].
  const InfoService();

  /// Creates a new [InfoService] with default implementation.
  /// https://pub.dev/packages/package_info_plus.
  factory InfoService.create() = _PackageInfoService;

  /// The app name.
  ///
  /// - `CFBundleDisplayName` on iOS and macOS, falls back to `CFBundleName`.
  ///   Defined in the `info.plist` and/or product target in xcode.
  /// - `application/label` on Android.
  ///   Defined in `AndroidManifest.xml` or String resources.
  /// - `app_name` from `version.json` on Web.
  ///   Defined in the `manifest.json`.
  /// - `app_name` from `version.json` on Linux.
  ///   Defined in the `CMakeLists.txt` file.
  /// - `ProductName` from the compiled executable file on Windows.
  ///    Defined in the `Runner.rc` file.
  String get name;

  /// The package name.
  ///
  /// - `bundleIdentifier` on iOS and macOS.
  ///   Defined in the product target in xcode.
  /// - `packageName` on Android.
  ///   Defined in `build.gradle` as `applicationId`.
  /// - `package_name` from `version.json` on Web and Linux
  ///   Generated by Flutter.
  /// - `InternalName` from the compiled executable file on Windows.
  ///   Defined in the `Runner.rc` file.
  String get package;

  /// The package version.
  /// Generated from the version in `pubspec.yaml`.
  ///
  /// - `CFBundleShortVersionString` on iOS and macOS.
  /// - `versionName` on Android.
  /// - `version` from `version.json` on Web and Linux.
  /// - `ProductVersion` from the compiled executable file on Windows.
  String get version;

  /// Initializes the [InfoService].
  Future<InfoService> init();

  /// Disposes the the [InfoService].
  Future<void> dispose();
}
