name: yaraui
description: "SoftYesTI's cross-platform Design System."

homepage: https://softyes.com.br
repository: https://github.com/softyesti/yaraui

version: 0.1.0

environment:
  sdk: ^3.11.4
  flutter: ^3.41.6

dependencies:
  flutter:
    sdk: flutter

  get_it: ^9.2.1
  flutter_acrylic: ^1.1.4
  fluentui_system_icons: ^1.1.273
  bitsdojo_window:
    git:
      ref: master
      path: bitsdojo_window/
      url: https://github.com/kingdomseed/desktop_title_bar_controls

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: false
