name: yaraui
description: SoftYesTI's cross-platform design system.

homepage: https://softyes.com.br
repository: https://github.com/softyesti/yaraui
issue_tracker: https://github.com/softyesti/yaraui/issues

platforms:
  ios:
  macos:
  linux:
  android:
  windows:

resolution: workspace

version: 0.1.0

environment:
  sdk: ^3.12.2
  flutter: ^3.44.9

dependencies:
  flutter:
    sdk: flutter

  get_it: ^9.2.1
  webview_all: ^1.2.1
  flutter_acrylic: ^1.1.4
  window_manager: ^0.5.2
  cupertino_icons: ^1.0.9
  solar_icon_pack: ^0.3.0
  package_info_plus: ^10.2.1
  fluentui_system_icons: ^1.1.273

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: false
