name: yaraui_mobile
description: Mobile implementations of YaraUI. SoftYesTI's cross-platform design system.

homepage: https://softyes.com.br
repository: https://github.com/softyesti/yaraui
issue_tracker: https://github.com/softyesti/yaraui/issues

platforms:
  ios:
  android:

resolution: workspace

version: 0.1.0

environment:
  sdk: ^3.12.2
  flutter: ^3.44.9

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: false
